[package]
name = "pangpang_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9"
pangpang = { path="../pangpang" }
iced = { version="0.3", features=["glow", "glow_default_system_font", "tokio"] }
iced_native = "0.4"

